name: 'Publish pack with next dist-tag'

on:
  workflow_dispatch:
  push:
    branches:
      - main

# TODO: use np for release template. basically it should be possible to use 1.4.1 as next version and then later tag it and release
jobs:
  testing:
    uses: ./.github/workflows/qa-check.yml

  publish-npm:
    needs: testing
    uses: beuluis/reusable-workflows/.github/workflows/publish-npm.yml@main
    with:
      dist_tag: 'next'
    secrets: inherit
