name: Next publish package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    uses: ./.github/workflows/qa-check.yml

  publish-npm:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Publish package
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
