on:
  push:
    branches:
      - main

jobs:
  testing:
    uses: ./.github/workflows/qa-check.yml

  publish-npm:
    needs: testing
    uses: beuluis/reusable-workflows/.github/workflows/publish-npm.yml@main
    with:
      dist_tag: 'next'
    secrets: inherit
